services:
  postgres:
    image: postgres:16
    container_name: mc_postgres
    environment:
      POSTGRES_USER: mc
      POSTGRES_PASSWORD: mc
      POSTGRES_DB: mc_orders
    ports:
      - "5432:5432"
    volumes:
      - mc_pg:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mc"]
      interval: 10s
      timeout: 5s
      retries: 5
  redis:
    image: redis:7
    container_name: mc_redis
    ports:
      - "6379:6379"
    volumes:
      - mc_redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mc_pg:
  mc_redis: